#!/usr/bin/env python3
"""Generate the bank tab row into bank_main.if, and register it in the interface packs.

WHY A GENERATOR. Nine tabs x three components each, with the pack ids, the order file and
the .rs2 handlers all having to agree, is exactly the shape that drifts when hand-edited.
genmenus.py exists for the same reason; this follows its rules.

THE RULES IT FOLLOWS (from genmenus.repack's docstring, learned the hard way there)
  - PackShared walks interface.order and looks every id up in interface.pack, so the two
    files must agree EXACTLY. An id in the order with no pack entry packs a component with
    type -1 and the client throws on load.
  - Rewrite rather than append: the generated block is dropped from both files first, so
    running this twice reuses the same ids instead of abandoning a block on every run.
  - interface.pack is LF. interface.order follows the repo's other text files. Mixing them
    up is a whole-file diff.

WHAT IT DRAWS
  Tab 0 ("All") is a rect plus a text label. Tabs 1-8 are a rect, a layer, and a model icon
  inside that layer. The icon needs its own LAYER because if_sethide only works on layers -
  an empty tab has to be able to hide its icon, and hiding the model directly does nothing.

  Highlighting is free: buttontype=select plus script1op1=pushvar,banktab / script1=eq,K is
  a client-side expression re-evaluated every frame, so switching tabs is one varp write and
  no packets. Same mechanism the Withdraw-as-Note buttons already use.

  Each rect carries clientcode CLIENTCODE_BASE+K. That is what the client patch hit-tests
  on drag release to turn "dropped on tab 3" into an INV_BUTTOND with mode = DRAG_TAB_BASE+3;
  without a clientcode the drop is indistinguishable from dropping on empty chrome.
"""
import os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bankgeom as G

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IF = os.path.join(ROOT, 'scripts/interface_bank/interfaces/bank_main.if')
PACK = os.path.join(ROOT, 'pack/interface.pack')
ORDER = os.path.join(ROOT, 'pack/interface.order')

MARK_A = '// ---- bank tabs (generated by tools/genbanktabs.py - do not hand edit below) ----'
MARK_B = '// ---- end bank tabs ----'

TABS = G.TABS
CLIENTCODE_BASE = 207        # 206 is the bank grid itself; the client keys off these
GRID_W = G.COLS              # columns in the bank grid; written onto the [bank] component below


def bank_slots():
    """^bank_total_slots, read from the config rather than repeated here. The grid has to have a
    cell for every slot, so this number and the row count below must never be allowed to drift."""
    src = open(os.path.join(ROOT, 'scripts/interface_bank/configs/bank.constant'),
               encoding='utf-8').read()
    m = re.search(r'^\^bank_total_slots = (\d+)', src, re.M)
    if not m:
        sys.exit('cannot find ^bank_total_slots in bank.constant')
    return int(m.group(1))

# Geometry: all of it from tools/bankgeom.py, which the window frame and the button row read too.
# The tab row is 32 tall, not 27. if_setobject draws an obj at roughly its inventory size, and a
# tall item - a vial, a staff - overflowed a 27px box top and bottom. Model components are clipped
# at the BOTTOM and nowhere else, so the overspill above sat on the window chrome.
ROW_Y, ROW_H = G.TAB_Y, G.TAB_H
TAB_X0, TAB_W, TAB_PITCH = G.TAB_X0, G.TAB_W, G.TAB_PITCH
GRID_X, GRID_Y, GRID_H = G.GRID_X, G.GRID_Y, G.GRID_H

# The grid needs a row for every slot AND for the padding. In the "all items" view each tab starts
# on a fresh row, so eight ragged tabs can burn up to GRID_W - 1 padding cells each and a grid
# sized to the inv alone would push the last of them off the bottom where they could not be
# scrolled to. So the row count is ceil((slots + padding) / GRID_W), read from bank.constant rather
# than written down twice. The spare cells at the end sit past the end of the inv, draw nothing,
# and are rejected by the engine's validSlot check if anyone manages to click one.
#
# The row count is what the grid costs to DRAW, and it is drawn every frame: the client walks all
# width x height cells of an inv component, but the icon work is behind a clip test
# (var20 > Pix2D.left - 32 && ... in drawInterface), so an off-screen cell costs two comparisons.
SLOT_PAD = (TABS - 1) * (GRID_W - 1)     # 8 numbered tabs x up to 7 wasted cells
GRID_ROWS = -(-(bank_slots() + SLOT_PAD) // GRID_W)

COL_OFF = '0x3E3529'         # unselected tab
COL_ON  = '0x6F6250'         # selected tab - matches the window's lit chrome

def blocks():
    out = [MARK_A, '']
    for k in range(TABS):
        x = TAB_X0 + k * TAB_PITCH
        out += [f'[banktab{k}]',
                'type=rect',
                f'x={x}',
                f'y={ROW_Y}',
                'buttontype=select',
                f'width={TAB_W}',
                f'height={ROW_H}',
                'script1op1=pushvar,banktab',
                f'script1=eq,{k}',
                'fill=yes',
                f'colour={COL_OFF}',
                f'activecolour={COL_ON}',
                f'clientcode={CLIENTCODE_BASE + k}',
                f'option=View tab {k}' if k else 'option=View all items',
                '']
    # tab 0 is the "all items" tab and never shows an item icon
    out += ['[banktab0text]',
            'type=text',
            f'x={TAB_X0}',
            f'y={ROW_Y + 10}',
            f'width={TAB_W}',
            'height=14',
            'center=yes',
            'font=p11_full',
            'shadowed=yes',
            'text=All',
            'colour=0xFF981F',
            '']
    for k in range(1, TABS):
        x = TAB_X0 + k * TAB_PITCH
        # the icon lives in its own layer so an empty tab can hide it - if_sethide is
        # layer-only, so a bare model component could never be hidden
        # the layer IS the tab box: an obj icon is drawn around the centre of its component, so
        # matching the box means the icon centres on the tab instead of on a smaller inset box
        out += [f'[banktab{k}icon]',
                'type=layer',
                f'x={x}',
                f'y={ROW_Y}',
                f'width={TAB_W}',
                f'height={ROW_H}',
                '']
        out += [f'[banktab{k}obj]',
                f'layer=banktab{k}icon',
                'type=model',
                'x=0',
                'y=0',
                f'width={TAB_W}',
                f'height={ROW_H}',
                '']
    out += [MARK_B, '']
    return '\n'.join(out)

def main():
    src = open(IF, encoding='utf-8', newline='').read()
    crlf = '\r\n' in src
    body = src.replace('\r\n', '\n')

    # drop any previous generated block, so a second run reuses the same ids
    # the \n* eats the blank lines the block was sitting behind as well. Without it the hole
    # left by the drop is added to by the '\n\n' the re-append puts back, and the file grows two
    # blank lines on every round trip - which is a whole-file diff waiting to happen the next
    # time somebody reformats, and is why this generator and genbankbar were not idempotent.
    body = re.sub(r'\n*' + re.escape(MARK_A) + r'.*?' + re.escape(MARK_B) + r'\n?', '', body, flags=re.S)

    # the scroll layer the grid lives in
    m = re.search(r'\[com_92\]\ntype=layer\n(?:[a-z0-9_]+=[^\n]*\n)+', body)
    if not m:
        sys.exit('com_92 does not look the way this generator expects - refusing to guess')
    # scroll is the layer's virtual content height. The client recomputes it per tab when it gets
    # if_setinvwindow / if_setinvbreaks, but the static value has to cover the full grid so a client
    # that has not been told anything yet can still scroll to the bottom.
    scroll = G.INV_Y + GRID_ROWS * G.PITCH
    body = body[:m.start()] + (f'[com_92]\ntype=layer\nx={GRID_X}\ny={GRID_Y}\nwidth={G.GRID_W}\n'
                               f'height={GRID_H}\nscroll={scroll}\n') + body[m.end():]

    # and the grid itself: its shape is this generator's business, its five withdraw options are
    # the content's, so only the geometry lines are rewritten
    g = re.search(r'(\[bank\]\nlayer=com_92\n)((?:[a-z0-9_]+=[^\n]*\n)+)', body)
    if not g:
        sys.exit('the bank grid does not look the way this generator expects')
    geom = {'x': str(G.INV_X), 'y': str(G.INV_Y), 'width': str(GRID_W), 'height': str(GRID_ROWS),
            'margin': f'{G.MARGIN},{G.MARGIN}'}
    lines = [l for l in g.group(2).split('\n') if l]
    seen = set()
    for i, l in enumerate(lines):
        k = l.split('=', 1)[0]
        if k in geom:
            lines[i] = f'{k}={geom[k]}'
            seen.add(k)
    missing = [k for k in geom if k not in seen]
    if missing:
        sys.exit(f'the bank grid has lost its {", ".join(missing)} - refusing to guess')
    body = body[:g.start()] + g.group(1) + '\n'.join(lines) + '\n' + body[g.end():]

    body = body.rstrip('\n') + '\n\n' + blocks()
    open(IF, 'w', encoding='utf-8', newline='').write(body.replace('\n', '\r\n') if crlf else body)

    names = [n for n in re.findall(r'^\[([A-Za-z0-9_]+)\]$', blocks(), re.M)]

    # ---- repack, obeying the pack/order agreement rule
    pack = [l for l in open(PACK, encoding='utf-8', newline='').read().replace('\r\n', '\n').split('\n') if l]
    order_raw = open(ORDER, encoding='utf-8', newline='').read()
    order_crlf = '\r\n' in order_raw
    order = [l for l in order_raw.replace('\r\n', '\n').split('\n') if l]

    # REUSE the ids this block already has rather than re-allocating at max+1. genmenus.py also
    # repacks by dropping its block and appending at max+1, and only one generator can own the tail
    # of the file: if both re-allocate, whichever runs second shoves the other's ids and neither is
    # idempotent any more (poh_battery checks exactly that for genmenus). Reusing means this one is
    # idempotent wherever it sits, and genmenus keeps the tail. Run genmenus AFTER this the first
    # time, so its block ends up above ours.
    existing = {}
    keep_pack, dropped = [], set()
    for l in pack:
        i, n = l.split('=', 1)
        if n.startswith('bank_main:banktab'):
            existing[n.split(':', 1)[1]] = i
            dropped.add(i)
            continue
        keep_pack.append(l)
    order = [l for l in order if l not in dropped]

    used = {int(l.split('=', 1)[0]) for l in keep_pack}
    nxt = max(used) + 1
    for n in names:
        if n in existing and int(existing[n]) not in used:
            i = existing[n]
        else:
            while nxt in used:
                nxt += 1
            i = str(nxt); nxt += 1
        used.add(int(i))
        keep_pack.append(f'{i}=bank_main:{n}')
        order.append(i)
    keep_pack.sort(key=lambda l: int(l.split('=', 1)[0]))
    order.sort(key=int)

    ids = [l.split('=', 1)[0] for l in keep_pack]
    assert len(ids) == len(set(ids)), 'duplicate interface id'
    nm = [l.split('=', 1)[1] for l in keep_pack]
    assert len(nm) == len(set(nm)), 'duplicate interface name'
    assert set(order) == set(ids), 'interface.order and interface.pack disagree'

    open(PACK, 'w', encoding='utf-8', newline='').write('\n'.join(keep_pack) + '\n')
    open(ORDER, 'w', encoding='utf-8', newline='').write(
        ('\r\n' if order_crlf else '\n').join(order) + ('\r\n' if order_crlf else '\n'))
    mine = sorted(int(l.split('=', 1)[0]) for l in keep_pack
                  if l.split('=', 1)[1].startswith('bank_main:banktab'))
    print(f'{len(names)} components, ids {mine[0]}..{mine[-1]}; '
          f'grid {GRID_W}x{GRID_ROWS} rows, {G.VISIBLE_ROWS} rows visible '
          f'({GRID_W * G.VISIBLE_ROWS} slots on screen); layer {GRID_X},{GRID_Y} '
          f'{G.GRID_W}x{GRID_H}')

main()
