#!/usr/bin/env python3
"""Generate the bank window itself - its backing, its frame and its title - into bank_main.if.

WHY A GENERATOR. The window used to be 89 hand-placed components: 30 backing tiles, four corners
and 55 bars, every one of them a literal x and y. That is fine as long as nobody ever moves the
window, and impossible the moment somebody does - which is what "make the bank bigger" asks for.
The frame is a rectangle; a rectangle is four numbers, and those four numbers live in
tools/bankgeom.py where the tab row and the button row can see them too.

It follows genbanktabs.py's rules to the letter - see its docstring for the pack/order agreement
rule and why the block is rewritten rather than appended. Run it BEFORE genbanktabs and genbankbar,
which position themselves against the same geometry.

WHAT IT DRAWS

  The interior, tiled with the 88x60 tradebacking sprite, then the frame on top of it: four 25x30
  steelborder corners and, between them, rows and columns of 36x36 edge tiles. An edge tile is
  almost entirely transparent - its content is a six-pixel bar down the middle, at rows 15..20 - so
  a bar whose top edge is at y sits in a component at y - 15, and the top and left rows of the frame
  therefore have negative coordinates. 377 did this too (the old left edge was at x=-3); the root is
  a 512x334 layer and Client.drawInterfaceLayer clips to it, so the overhang costs nothing.

  The last tile of every run is pulled back to finish flush on the edge rather than overhang it,
  which is what the original did with its backing row (x=412, not x=452). The tiles are a repeating
  texture, so the overlap does not show.

  com_90 (the caption) and com_91 (the close link) keep their ids and their [if_button]/close
  behaviour and are simply moved onto the new title bar. The caption is centred by the client now
  rather than by a hand-measured x.

WHICH IDS IT USES. The 89 chrome components it replaces are dropped, and their ids go back into a
pool that the new components are handed first. So a window with the same number of tiles reuses
exactly the ids the old one had, and only the overflow lands at the end of interface.pack.
"""
import os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bankgeom as G

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IF = os.path.join(ROOT, 'scripts/interface_bank/interfaces/bank_main.if')
PACK = os.path.join(ROOT, 'pack/interface.pack')
ORDER = os.path.join(ROOT, 'pack/interface.order')

MARK_A = '// ---- bank window (generated by tools/genbankframe.py - do not hand edit below) ----'
MARK_B = '// ---- end bank window ----'

# Everything the generated frame replaces: the backing, the corners and every edge tile, plus
# com_88, an empty layer over the old window that nothing was ever a child of.
DEAD = [f'com_{n}' for n in range(0, 89)]

BACKING = ('tradebacking', 0, 88, 60)
CORNER_W, CORNER_H = 25, 30
EDGE = 36                      # a frame tile
CAPTION = 'The Bank of Gielinor'


def blocks():
    out = [MARK_A, '']

    def com(name, x, y, w, h, graphic):
        out.extend([f'[{name}]', 'type=graphic', f'x={x}', f'y={y}',
                    f'width={w}', f'height={h}', f'graphic={graphic}', ''])

    # ---- the interior, tiled. It runs from the outer edge of the left/top bars to the outer edge
    # of the right bar and the inner edge of the bottom one, exactly as the 377 window did.
    sheet, idx, tw, th = BACKING
    n = 0
    for y in G.tiles(G.FRAME_T, G.FRAME_B + 1, th):
        for x in G.tiles(G.FRAME_L, G.FRAME_R + G.BAR, tw):
            com(f'bankbg{n}', x, y, tw, th, f'{sheet},{idx}')
            n += 1

    # ---- the frame. A bar at Y is a tile at Y - BAR_OFF; the corners are drawn at their own size.
    top, bottom = G.FRAME_T - G.BAR_OFF, G.FRAME_B - G.BAR_OFF
    left, right = G.FRAME_L - G.BAR_OFF, G.FRAME_R - G.BAR_OFF
    # the span the horizontal runs cover: between the corners
    hx0, hx1 = G.FRAME_L + CORNER_W, G.FRAME_R + G.BAR - CORNER_W
    # and the vertical ones: from just inside the top corners to just inside the bottom ones
    vy0, vy1 = G.FRAME_T + CORNER_H - 1, G.FRAME_B + G.BAR - CORNER_H

    for i, x in enumerate(G.tiles(hx0, hx1, EDGE)):
        com(f'bankframe_top{i}', x, top, EDGE, EDGE, 'steelborder2,0')
    for i, x in enumerate(G.tiles(hx0, hx1, EDGE)):
        com(f'bankframe_bottom{i}', x, bottom, EDGE, EDGE, 'miscgraphics,3')
    for i, y in enumerate(G.tiles(vy0, vy1, EDGE)):
        com(f'bankframe_left{i}', left, y, EDGE, EDGE, 'miscgraphics,2')
    for i, y in enumerate(G.tiles(vy0, vy1, EDGE)):
        com(f'bankframe_right{i}', right, y, EDGE, EDGE, 'steelborder2,1')
    # the rule under the title spans the whole interior - it has no corners to stop at
    for i, x in enumerate(G.tiles(G.FRAME_L + G.BAR - 1, G.FRAME_R + 1, EDGE)):
        com(f'bankframe_rule{i}', x, G.SEP_Y - G.BAR_OFF, EDGE, EDGE, 'steelborder2,0')

    for i, (x, y) in enumerate([(G.FRAME_L, G.FRAME_T),
                                (G.FRAME_R + G.BAR - CORNER_W, G.FRAME_T),
                                (G.FRAME_L, G.FRAME_B + G.BAR - CORNER_H),
                                (G.FRAME_R + G.BAR - CORNER_W, G.FRAME_B + G.BAR - CORNER_H)]):
        com(f'bankframe_corner{i}', x, y, CORNER_W, CORNER_H, f'steelborder,{i}')

    out += [MARK_B, '']
    return '\n'.join(out)


def retitle(body):
    """Move com_90 and com_91 onto the new title bar, keeping their ids and their behaviour."""
    m = re.search(r'\[com_90\]\n(?:[a-z0-9_]+=[^\n]*\n)+', body)
    if not m:
        sys.exit('com_90 (the bank caption) does not look the way this generator expects')
    block = '\n'.join(['[com_90]', 'type=text', f'x={G.IN_L}', f'y={G.TITLE_Y}',
                       f'width={G.IN_W}', 'height=14', 'center=yes', 'font=b12_full',
                       'shadowed=yes', f'text={CAPTION}', 'colour=0xFF981F']) + '\n'
    body = body[:m.start()] + block + body[m.end():]

    m = re.search(r'\[com_91\]\n(?:[a-z0-9_]+=[^\n]*\n)+', body)
    if not m:
        sys.exit('com_91 (the close link) does not look the way this generator expects')
    block = '\n'.join(['[com_91]', 'type=text',
                       f'x={G.IN_R - 6 - G.CLOSE_W}', f'y={G.CLOSE_Y}',
                       'buttontype=close', f'width={G.CLOSE_W}', f'height={G.CLOSE_H}',
                       'font=p11_full', 'shadowed=yes', 'text=Close Window',
                       'colour=0x808080', 'overcolour=0xFFFFFF']) + '\n'
    return body[:m.start()] + block + body[m.end():]


def main():
    src = open(IF, encoding='utf-8', newline='').read()
    crlf = '\r\n' in src
    body = src.replace('\r\n', '\n')

    # drop any previous generated block, so a second run reuses the same ids. The \n* eats the
    # blank lines it was sitting behind as well, or the file grows two of them on every round trip.
    body = re.sub(r'\n*' + re.escape(MARK_A) + r'.*?' + re.escape(MARK_B) + r'\n?', '', body,
                  flags=re.S)
    body = retitle(body)
    for com in DEAD:
        m = re.search(r'\[' + com + r'\]\n(?:[a-z0-9_]+=[^\n]*\n)+\n?', body)
        if m:
            body = body[:m.start()] + body[m.end():]

    # the window goes FIRST: the client draws children in order, so everything else has to be
    # painted over it
    body = blocks() + '\n' + body.lstrip('\n')
    open(IF, 'w', encoding='utf-8', newline='').write(body.replace('\n', '\r\n') if crlf else body)

    names = re.findall(r'^\[([A-Za-z0-9_]+)\]$', blocks(), re.M)

    # ---- repack, obeying the pack/order agreement rule (genbanktabs.py's docstring has it)
    pack = [l for l in open(PACK, encoding='utf-8', newline='').read()
            .replace('\r\n', '\n').split('\n') if l]
    order_raw = open(ORDER, encoding='utf-8', newline='').read()
    order_crlf = '\r\n' in order_raw
    order = [l for l in order_raw.replace('\r\n', '\n').split('\n') if l]

    mine = {f'bank_main:{n}' for n in names}
    dead = {f'bank_main:{n}' for n in DEAD}
    existing, keep_pack, dropped, freed = {}, [], set(), []
    for l in pack:
        i, n = l.split('=', 1)
        if n in mine:
            existing[n.split(':', 1)[1]] = i
            dropped.add(i)
            continue
        if n in dead:
            # the ids the old chrome held: handed out again below rather than abandoned
            dropped.add(i)
            freed.append(int(i))
            continue
        keep_pack.append(l)
    order = [l for l in order if l not in dropped]

    used = {int(l.split('=', 1)[0]) for l in keep_pack}
    freed = sorted(i for i in freed if i not in used)
    nxt = max(used) + 1
    for n in names:
        if n in existing and int(existing[n]) not in used:
            i = existing[n]
        elif freed:
            i = str(freed.pop(0))
        else:
            while nxt in used:
                nxt += 1
            i = str(nxt); nxt += 1
        used.add(int(i))
        keep_pack.append(f'{i}=bank_main:{n}')
        order.append(i)
    keep_pack.sort(key=lambda l: int(l.split('=', 1)[0]))
    order.sort(key=int)

    ids = [l.split('=', 1)[0] for l in keep_pack]
    assert len(ids) == len(set(ids)), 'duplicate interface id'
    nm = [l.split('=', 1)[1] for l in keep_pack]
    assert len(nm) == len(set(nm)), 'duplicate interface name'
    assert set(order) == set(ids), 'interface.order and interface.pack disagree'

    open(PACK, 'w', encoding='utf-8', newline='').write('\n'.join(keep_pack) + '\n')
    open(ORDER, 'w', encoding='utf-8', newline='').write(
        ('\r\n' if order_crlf else '\n').join(order) + ('\r\n' if order_crlf else '\n'))
    got = sorted(int(l.split('=', 1)[0]) for l in keep_pack if l.split('=', 1)[1] in mine)
    print(f'{len(names)} components, ids {got[0]}..{got[-1]}; window '
          f'{G.FRAME_L},{G.FRAME_T}..{G.FRAME_R + G.BAR},{G.FRAME_B + G.BAR}; '
          f'{len(freed)} freed ids left over')


main()
