#!/usr/bin/env python3
"""Generate the bank's bottom button bar into bank_main.if, and register it in the interface packs.

WHY A GENERATOR. Same reason as tools/genbanktabs.py: twelve buttons, their icon overlays, their
labels, the pack ids and the order file all have to agree, and that is exactly the shape that
drifts when hand-edited. This follows genbanktabs' rules to the letter - see its docstring for
the pack/order agreement rule and why the block is rewritten rather than appended.

WHAT IT DRAWS

  A single 36px row of twelve OSRS-style buttons across the bottom of the bank window:

    [Swap][Insert]  [Note]  [1][5][10][X][All]  [Search][Lock]  [Dep inv][Dep worn]

  centred on the window, whose width and button row live in tools/bankgeom.py. THAT IS THE BUDGET:
  a button past the frame is refused below rather than drawn under it. OSRS has a smaller 31x32
  button background at 174/177 if the row ever has to grow past what the width allows.

  Swap/Insert are two components that were already there - com_99 and com_100 - moved onto the row
  and restyled. They keep their ids, their buttontype=select scripts and their [if_button]s.

  WITHDRAW-AS IS ONE BUTTON, NOT TWO. It used to be a com_94 / com_93 radio pair with "Item" and
  "Note" labels under them. Two states of one setting is a toggle, so it is now a single button
  showing the note icon, lit while %bankcert is 1 - and com_94 is deleted along with the six text
  labels the icons replace. buttontype=toggle plus script1op1=pushvar makes the CLIENT flip the
  varp for itself (Client.java: `varps[v] = 1 - varps[v]` when scripts[0][0] == 5, which is what
  pushvar packs to), so the highlight moves on the same frame as the click and the server's
  [if_button] only has to mirror it.

  Every button is the same pair of sprites - bankbuttons,0 unlit and bankbuttons,1 lit - with a
  separate non-button graphic component drawn on top carrying the icon. That split is what makes
  the highlight free: the background switches on a client-side varp comparison and the icon never
  moves. The icon components are not buttons, so they are skipped by the hit test and do not
  swallow the click.

  The quantity buttons carry a text label rather than an icon. The X button's label is rewritten
  by the server with if_settext once a custom amount has been entered, so it reads "250" the way
  OSRS does rather than staying "X".

  The Search button is the one button the server never hears about: clientcode 221 plus
  buttontype=normal means the client's handleInterfaceAction intercepts it, opens the search box
  and returns false, so no packet is sent. The filter is a view of an inv the client already has.

SPRITE SHEET. sprites/bankbuttons.png is a 10-tile 36x36 strip built by
tools/models/genbanksprites.py out of the OSRS cache. Index order is fixed by BG_OFF/BG_ON/ICON_*
below. Tile 4 (the "item" half of the old withdraw-as pair) is no longer drawn, but it stays in
the sheet so every index after it keeps its number.
"""
import os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bankgeom as G

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IF = os.path.join(ROOT, 'scripts/interface_bank/interfaces/bank_main.if')
PACK = os.path.join(ROOT, 'pack/interface.pack')
ORDER = os.path.join(ROOT, 'pack/interface.order')

MARK_A = '// ---- bank bottom bar (generated by tools/genbankbar.py - do not hand edit below) ----'
MARK_B = '// ---- end bank bottom bar ----'

SHEET = 'bankbuttons'
BG_OFF, BG_ON = 0, 1
ICON_SWAP, ICON_INSERT, ICON_ITEM, ICON_NOTE = 2, 3, 4, 5
ICON_SEARCH, ICON_DEPINV, ICON_DEPWORN, ICON_LOCK = 6, 7, 8, 9

ROW_Y, BTN = G.BTN_Y, G.BTN
X0, PITCH = G.BTN_X0, G.BTN_PITCH
RIGHT_EDGE = G.IN_R       # the window's right-hand steel border starts here

# The existing components this generator restyles in place, as (name, slot, icon, suffix, kind).
# 'select' keeps the component's own script1op1/script1 lines; 'toggle' is rewritten to flip.
KEEP = [('com_99', 0, ICON_SWAP, 'swap', 'select'),
        ('com_100', 1, ICON_INSERT, 'insert', 'select'),
        ('com_93', 2, ICON_NOTE, 'note', 'toggle')]

# com_94 was the "Item" half of the withdraw-as pair; the rest are the six text labels.
DEAD = ['com_94', 'com_95', 'com_96', 'com_97', 'com_98', 'com_101', 'com_102']

QTY = [('bankqty1', 3, 0, '1', 'Withdraw 1 at a time'),
       ('bankqty5', 4, 1, '5', 'Withdraw 5 at a time'),
       ('bankqty10', 5, 2, '10', 'Withdraw 10 at a time'),
       ('bankqtyx', 6, 3, 'X', 'Withdraw a custom amount'),
       ('bankqtyall', 7, 4, 'All', 'Withdraw everything')]

SEARCH_CLIENTCODE = 221
SEARCH_SLOT, LOCK_SLOT, DEPINV_SLOT, DEPWORN_SLOT = 8, 9, 10, 11
SLOTS = G.BTN_SLOTS


def slot_x(i):
    return X0 + i * PITCH


def blocks():
    out = [MARK_A, '']
    # icon overlays for the three components that already exist above
    for com, i, icon, name, kind in KEEP:
        out += [f'[bankicon_{name}]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                f'width={BTN}',
                f'height={BTN}',
                f'graphic={SHEET},{icon}',
                '']
    # quantity buttons
    for name, i, value, label, option in QTY:
        out += [f'[{name}]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                'buttontype=select',
                f'width={BTN}',
                f'height={BTN}',
                'script1op1=pushvar,bankquantity',
                f'script1=eq,{value}',
                f'graphic={SHEET},{BG_OFF}',
                f'activegraphic={SHEET},{BG_ON}',
                f'option={option}',
                '']
    # The placeholder padlock. A component carries exactly ONE option string (PackShared writes a
    # single pjstr for it), so "Release all placeholders" gets its own invisible button stacked on
    # the same rectangle - a type=graphic with no graphic= draws nothing but still hit-tests. It is
    # emitted FIRST so the visible toggle, coming second, is the one the left click takes: the menu
    # is built in child order and useMenuOption takes menuSize - 1.
    out += ['[banklockrelease]',
            'type=graphic',
            f'x={slot_x(LOCK_SLOT)}',
            f'y={ROW_Y}',
            'buttontype=normal',
            f'width={BTN}',
            f'height={BTN}',
            'option=Release all placeholders',
            '']
    out += ['[banklock]',
            'type=graphic',
            f'x={slot_x(LOCK_SLOT)}',
            f'y={ROW_Y}',
            'buttontype=toggle',
            f'width={BTN}',
            f'height={BTN}',
            'script1op1=pushvar,bankplaceholders',
            'script1=eq,1',
            f'graphic={SHEET},{BG_OFF}',
            f'activegraphic={SHEET},{BG_ON}',
            'option=Always set placeholders',
            '']
    out += ['[banklockicon]',
            'type=graphic',
            f'x={slot_x(LOCK_SLOT)}',
            f'y={ROW_Y}',
            f'width={BTN}',
            f'height={BTN}',
            f'graphic={SHEET},{ICON_LOCK}',
            '']
    # the three plain action buttons
    for name, i, icon, option, clientcode in [
            ('banksearch', SEARCH_SLOT, ICON_SEARCH, 'Search', SEARCH_CLIENTCODE),
            ('bankdepinv', DEPINV_SLOT, ICON_DEPINV, 'Deposit inventory', None),
            ('bankdepworn', DEPWORN_SLOT, ICON_DEPWORN, 'Deposit worn items', None)]:
        out += [f'[{name}]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                'buttontype=normal',
                f'width={BTN}',
                f'height={BTN}',
                f'graphic={SHEET},{BG_OFF}',
                f'activegraphic={SHEET},{BG_ON}']
        if clientcode is not None:
            out += [f'clientcode={clientcode}']
        out += [f'option={option}', '']
        out += [f'[{name}icon]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                f'width={BTN}',
                f'height={BTN}',
                f'graphic={SHEET},{icon}',
                '']
    # quantity labels last, so they sit on top of their buttons
    for name, i, value, label, option in QTY:
        out += [f'[{name}text]',
                'type=text',
                f'x={slot_x(i)}',
                f'y={ROW_Y + 11}',
                f'width={BTN}',
                'height=14',
                'center=yes',
                'font=p11_full',
                'shadowed=yes',
                f'text={label}',
                'colour=0xFF981F',
                '']
    out += [MARK_B, '']
    return '\n'.join(out)


def main():
    right = slot_x(SLOTS - 1) + BTN
    if right > RIGHT_EDGE:
        sys.exit(f'the row ends at x={right}, past the window frame at {RIGHT_EDGE}')

    src = open(IF, encoding='utf-8', newline='').read()
    crlf = '\r\n' in src
    body = src.replace('\r\n', '\n')

    # the \n* eats the blank lines the block was sitting behind as well. Without it the hole
    # left by the drop is added to by the '\n\n' the re-append puts back, and the file grows two
    # blank lines on every round trip - which is a whole-file diff waiting to happen the next
    # time somebody reformats, and is why this generator and genbankbar were not idempotent.
    body = re.sub(r'\n*' + re.escape(MARK_A) + r'.*?' + re.escape(MARK_B) + r'\n?', '', body, flags=re.S)

    # restyle the components that keep their ids
    for com, i, icon, name, kind in KEEP:
        m = re.search(r'\[' + com + r'\]\n(?:[a-z0-9_]+=[^\n]*\n)+', body)
        if not m:
            sys.exit(f'{com} does not look the way this generator expects - refusing to guess')
        existing = dict(l.split('=', 1) for l in m.group(0).strip().split('\n')[1:] if '=' in l)
        if 'script1op1' not in existing:
            sys.exit(f'{com} has lost its interface script - refusing to guess')
        if kind == 'toggle':
            # the comparator only decides which way round the sprite lights; the click itself is
            # the client's own 1 - varp flip, which buttontype=toggle + pushvar is what triggers
            script = [f"script1op1={existing['script1op1']}", 'script1=eq,1']
        else:
            script = [f"script1op1={existing['script1op1']}", f"script1={existing['script1']}"]
        block = ([f'[{com}]',
                  'type=graphic',
                  f'x={slot_x(i)}',
                  f'y={ROW_Y}',
                  f'buttontype={kind}',
                  f'width={BTN}',
                  f'height={BTN}']
                 + script
                 + [f'graphic={SHEET},{BG_OFF}', f'activegraphic={SHEET},{BG_ON}'])
        body = body[:m.start()] + '\n'.join(block) + '\n' + body[m.end():]

    # drop the components the icons and the toggle replace
    for com in DEAD:
        m = re.search(r'\[' + com + r'\]\n(?:[a-z0-9_]+=[^\n]*\n)+\n?', body)
        if m:
            body = body[:m.start()] + body[m.end():]

    body = body.rstrip('\n') + '\n\n' + blocks()
    open(IF, 'w', encoding='utf-8', newline='').write(body.replace('\n', '\r\n') if crlf else body)

    names = re.findall(r'^\[([A-Za-z0-9_]+)\]$', blocks(), re.M)

    # ---- repack. Ids for this block are reused where they already exist (genbanktabs' rule:
    # only one generator can own the tail of interface.pack, and that one is genmenus).
    pack = [l for l in open(PACK, encoding='utf-8', newline='').read().replace('\r\n', '\n').split('\n') if l]
    order_raw = open(ORDER, encoding='utf-8', newline='').read()
    order_crlf = '\r\n' in order_raw
    order = [l for l in order_raw.replace('\r\n', '\n').split('\n') if l]

    mine = {f'bank_main:{n}' for n in names}
    dead = {f'bank_main:{n}' for n in DEAD}
    existing, keep_pack, dropped = {}, [], set()
    for l in pack:
        i, n = l.split('=', 1)
        if n in mine:
            existing[n.split(':', 1)[1]] = i
            dropped.add(i)
            continue
        if n in dead:
            dropped.add(i)
            continue
        keep_pack.append(l)
    order = [l for l in order if l not in dropped]

    used = {int(l.split('=', 1)[0]) for l in keep_pack}
    nxt = max(used) + 1
    for n in names:
        if n in existing and int(existing[n]) not in used:
            i = existing[n]
        else:
            while nxt in used:
                nxt += 1
            i = str(nxt); nxt += 1
        used.add(int(i))
        keep_pack.append(f'{i}=bank_main:{n}')
        order.append(i)
    keep_pack.sort(key=lambda l: int(l.split('=', 1)[0]))
    order.sort(key=int)

    ids = [l.split('=', 1)[0] for l in keep_pack]
    assert len(ids) == len(set(ids)), 'duplicate interface id'
    nm = [l.split('=', 1)[1] for l in keep_pack]
    assert len(nm) == len(set(nm)), 'duplicate interface name'
    assert set(order) == set(ids), 'interface.order and interface.pack disagree'

    open(PACK, 'w', encoding='utf-8', newline='').write('\n'.join(keep_pack) + '\n')
    open(ORDER, 'w', encoding='utf-8', newline='').write(
        ('\r\n' if order_crlf else '\n').join(order) + ('\r\n' if order_crlf else '\n'))
    got = sorted(int(l.split('=', 1)[0]) for l in keep_pack if l.split('=', 1)[1] in mine)
    print(f'{len(names)} components, ids {got[0]}..{got[-1]}; '
          f'row y={ROW_Y}, x {slot_x(0)}..{right}; dropped {len(DEAD)}')


main()
