#!/usr/bin/env python3
"""Write everything the boss kill counts need, from tools/bosskillspec.json.

WHY A GENERATOR. Every boss lands in five places - a varp, an index, a name, an increment, a read,
and a row in a window - which is eighty-odd entries that all have to agree about which boss is
which. A single one out of step is a counter that counts the wrong monster, and nothing errors.

THE ENGINE CANNOT PICK A VARP AT RUNTIME. engine.rs2 has no varp commands and no enum outputs one,
so there is no %vars[$i]. The increment and the read are therefore GENERATED switch_int procs with
one case per boss, and the two things that CAN be tables are tables: npc -> index and index -> name.

ONE BOSS CAN BE SEVERAL NPC RECORDS. Zulrah is three - one snake that changes colour with
npc_changetype_keepall - so a boss's optional "forms" list names the other records it can die in and
every one of them maps to that boss's single slot. It is a mapping, not a count: only one of them
ever dies, because keepall changes the type of one npc rather than adding another.

    python3 tools/genbosskills.py            # write the five files and take pack ids
    python3 tools/genbosskills.py --check     # exit 1 if any of them would change
"""
import json, os, re, sys

C = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(C, 'tools', 'bosskillspec.json')
IFACE = 'boss_kills'
OUT_VARP = os.path.join(C, 'scripts/bosses/configs/boss_kills.varp')
OUT_CONST = os.path.join(C, 'scripts/bosses/configs/boss_kills.constant')
OUT_ENUM = os.path.join(C, 'scripts/bosses/configs/boss_kills.enum')
OUT_IF = os.path.join(C, 'scripts/bosses/interfaces/boss_kills.if')
OUT_RS2 = os.path.join(C, 'scripts/bosses/scripts/boss_kills.rs2')
QUESTLIST = os.path.join(C, 'scripts/interfaces/questlist.if')
VARPPACK = os.path.join(C, 'pack/varp.pack')
IFPACK = os.path.join(C, 'pack/interface.pack')
IFORDER = os.path.join(C, 'pack/interface.order')

# The window: 377's smithing frame (genmenus.window, as the collection log and the Construction
# windows have it), and the bosses as a grid of boxes set into it - two columns, filled down the
# left first - each with the boss's name on the left and its count right-aligned on the right. The
# boxes are the quest tab's (genquesttab.Page.box): a translucent black face, dark along the top and
# left, brown along the bottom and right.
GRID_X, GRID_Y, COLS, COL_GAP = 24, 68, 2, 8
BOX_W, BOX_H, PITCH_Y = 228, 30, 34
PAD = 10
COL_NAME = '0xFF981F'
COL_COUNT = '0xFFFF00'
EDGE, RIM = '0x2E2B23', '0x726451'
# The row this used to append to the quest list, which patch_questlist now takes back out.
QL_ROW = 'boss_kills'


def read(p):
    return open(p, newline='').read().replace('\r\n', '\n')


def npcs_of(b):
    """Every npc record this boss can die in: its own, then whatever "forms" names.

    Only Zulrah has more than one, and the spec's "_forms" says why. tools/boss_battery.py reads
    this same helper's shape out of the delivered enum, so a form added here and not regenerated
    goes red rather than quietly counting nothing."""
    return [b['npc']] + list(b.get('forms', []))


def build_varp(spec):
    L = ['// ONE PERM VARP PER BOSS. GENERATED - do not hand-edit.',
         '//   python3 tools/genbosskills.py',
         '//',
         '// One separate varp each rather than bits in one, because a kill count has no ceiling a',
         '// bit range could hold - four bits stop at fifteen - and a varp is a full int.',
         '//',
         '// NOT TRANSMITTED. The window is filled by if_settext when it opens, so the client never',
         '// needs the numbers; nothing reads them client-side and nothing draws from them.',
         '//',
         '// protect=no IS WHAT MAKES THIS WORK AT ALL, and it cost four builds to find. Varps are',
         '// PROTECTED by default, and writing a protected varp needs the p_active_player pointer -',
         '// which an npc-context death does not have, whatever npc_findhero returns. The build',
         '// failed with "Attempt to access corrupted pointer" at the call site in npc_death.rs2,',
         '// and moving the guard, inlining the switch and dropping the queue all changed nothing',
         '// because none of them was the cause. skill_guide.varp explains the same rule for',
         '// [if_button] triggers, and %barrows_killed_monster - the closest thing in the tree, and',
         '// the template for this whole round - is a varbit on a base varp that carries it.',
         '']
    for b in spec['bosses']:
        L.append('// %s (%s, level %d)' % (b['name'], ', '.join(npcs_of(b)), b['vislevel']))
        L.append('[boss_kc_%s]' % b['key'])
        L.append('scope=perm')
        L.append('protect=no')
        L.append('')
    return '\n'.join(L)


def build_const(spec):
    return '\n'.join([
      '// GENERATED by tools/genbosskills.py - do not hand-edit.',
      '//',
      '// How many bosses keep a count. Everything that loops over them reads this rather than a',
      '// number, so the next boss is a line in tools/bosskillspec.json and a regenerate.',
      '^boss_kills_count = %d' % len(spec['bosses']),
      '^boss_kills_none = -1',
      '',
    ])


def build_enum(spec):
    B = spec['bosses']
    L = ['// WHICH BOSS, AND WHAT IT IS CALLED. GENERATED - do not hand-edit.',
         '//   python3 tools/genbosskills.py',
         '//',
         '// These two are tables because they CAN be: an npc maps to an int and an int maps to a',
         '// string, and enum() does both. The increment and the read cannot be tables, because',
         '// this engine has no way to pick a varp at runtime - those are generated switches in',
         '// boss_kills.rs2, and this comment is the reason they look different.',
         '',
         '[boss_kill_index]',
         '// the dying npc -> its slot, or ^boss_kills_none for everything else in the game',
         '//',
         "// A boss with more than one record here - Zulrah's three colours - lists every one of them",
         '// against the SAME slot. That is a mapping and not a double count: the colour change is',
         '// npc_changetype_keepall on one snake, so only one of the three ever dies.',
         'inputtype=npc',
         'outputtype=int',
         'default=-1']
    for i, b in enumerate(B):
        for npc in npcs_of(b):
            L.append('val=%s,%d' % (npc, i))
    L += ['',
          '[boss_kill_name]',
          "// slot -> the name off the boss's own npc record, so the window cannot disagree with",
          '// what the player sees over its head',
          'inputtype=int',
          'outputtype=string',
          'default=null']
    for i, b in enumerate(B):
        L.append('val=%d,%s' % (i, b['name']))
    L.append('')
    return '\n'.join(L)


def build_if(spec):
    sys.path.insert(0, os.path.join(C, 'tools'))
    import genmenus as G
    B = spec['bosses']
    out, names = [], []

    def com(nm, **kv):
        names.append(nm)
        out.append('[%s]' % nm)
        for k, v in kv.items():
            out.append('%s=%s' % (k, v))
        out.append('')

    out += ['// THE BOSS KILL WINDOW. GENERATED - do not hand-edit.',
            '//   python3 tools/genbosskills.py',
            '//',
            '// Opened from the quest tab (Server Statistics, Quick actions). The counts are pushed in',
            '// with if_settext when it opens rather than transmitted, so the varps stay',
            '// server-side and there is nothing to keep in sync.',
            '']
    for nm, kv in G.window('Boss Kill Counts'):
        if nm == 'subtitle':
            # the total, written by ~boss_kills_open
            kv = dict(kv, colour=COL_NAME)
        com(nm, **kv)
    rows = (len(B) + COLS - 1) // COLS
    for i, b in enumerate(B):
        col, row = divmod(i, rows)
        x = GRID_X + col * (BOX_W + COL_GAP)
        y = GRID_Y + row * PITCH_Y
        com('box%d' % i, type='rect', x=x + 1, y=y + 1, width=BOX_W - 2, height=BOX_H - 2, fill='yes',
            colour='0x000000', trans=146)
        com('box%d_rim' % i, type='rect', x=x, y=y, width=BOX_W, height=BOX_H, colour=RIM)
        com('box%d_top' % i, type='rect', x=x, y=y, width=BOX_W - 1, height=1, fill='yes', colour=EDGE)
        com('box%d_left' % i, type='rect', x=x, y=y, width=1, height=BOX_H - 1, fill='yes', colour=EDGE)
        com('name%d' % i, type='text', x=x + PAD, y=y + 8, width=BOX_W - 2 * PAD, height=15,
            font='p12_full', shadowed='yes', colour=COL_NAME, text=b['name'])
        # Left-aligned across the box, and moved right by the width its number leaves empty when the
        # window opens (377 text is left-aligned or centred). It starts at 0 rather than blank: an
        # empty row reads as a broken window.
        com('count%d' % i, type='text', x=x + PAD, y=y + 8, width=BOX_W - 2 * PAD, height=15,
            font='b12_full', shadowed='yes', colour=COL_COUNT, text='0')
    return '\n'.join(out), names


def build_rs2(spec):
    B = spec['bosses']
    L = ['// THE BOSS KILL COUNTS. GENERATED - do not hand-edit.',
         '//   python3 tools/genbosskills.py',
         '//',
         '// ~boss_kill_record is called from [proc,npc_death], which is the one funnel every death',
         '// in the game passes through - and the only one available, because a second [ai_queue3]',
         '// on an npc that already has one is a hard build error and most of these already have',
         '// theirs for a drop table. ~barrows_potential hangs off the same place for the same',
         '// reason, and is the template for the whole shape of this file. Zulrah is the one that',
         '// looks like an exception and is not: its [ai_queue3] IS its own death script, and the',
         '// first line of that script is gosub(npc_death), so its kill arrives here like the rest.',
         '//',
         '// CREDIT IS npc_findhero, the test every drop table in this tree opens with, so a kill',
         '// counts for exactly the player the loot went to. %npc_aggressive_player is the LAST',
         '// attacker and is a different thing. Slayer deliberately SPLITS a task kill when those',
         '// two differ; a kill count is not split, because two players each being told they killed',
         '// the same boss is a wrong number rather than a generous one.',
         '//',
         '// THE MESSAGE IS QUEUED because mes() wants a player context an npc-context death does',
         '// not have. The COUNTER is not queued: protect=no on the varps is what lets it be',
         '// written from here, and boss_kills.varp says why at length. Four builds were spent',
         '// moving this guard, inlining a switch and dropping a queue before the varp',
         '// declaration turned out to be the answer - the same answer %barrows_killed_monster',
         '// has had the whole time, on a base varp that carries protect=no.',
         '//',
         '// THE GUARD IS THE FIRST THING IN THE PROC, and it is about CREDIT rather than about',
         '// the pointer. Without it the counter would be written for whoever the death context',
         '// happened to be pointing at. It went missing for one build while the pointer error was',
         '// being chased, and the build went GREEN with it gone - which is the whole reason the',
         '// battery checks for it by name.',
         '[proc,boss_kill_record]',
         'if (npc_findhero = ^false) {',
         '    return;',
         '}',
         'def_int $slot = enum(npc, int, boss_kill_index, npc_type);',
         'if ($slot = ^boss_kills_none) {',
         '    return;',
         '}',
         '// ONE CASE PER BOSS, ALL IN THE OPEN. This is what "the engine cannot pick a varp at',
         '// runtime" costs, and there is no way to spend less: no %vars[$i], no enum that outputs',
         '// a varp. A default case, so a slot outside the table does nothing rather than',
         "// incrementing the first boss's counter.",
         'switch_int ($slot) {']
    for i, b in enumerate(B):
        L.append('    case %d : %%boss_kc_%s = add(%%boss_kc_%s, 1);' % (i, b['key'], b['key']))
    L += ['    case default : return;',
          '}',
          'queue(boss_kill_announce, 0, $slot);',
          '',
          '// THE MESSAGE IS QUEUED, because mes() wants a player context an npc-context death does',
          '// not have. The queue re-reads the count rather than being handed it, so the number the',
          '// player is told is the number that is stored.',
          '[queue,boss_kill_announce](int $slot)',
          'mes("Your <enum(int, string, boss_kill_name, $slot)> kill count is: '
          '<tostring(~boss_kill_get($slot))>.");',
          '',
          '// THE READ-BACK SWITCH. This is the other half of what "no runtime varp index" costs:',
          '// one case per boss to read one counter. A default of 0, so a slot outside the table',
          "// reads as no kills rather than as the first boss's.",
          '[proc,boss_kill_get](int $slot)(int)',
          'switch_int ($slot) {']
    for i, b in enumerate(B):
        L.append('    case %d : return(%%boss_kc_%s);' % (i, b['key']))
    L += ['    case default : return(0);',
          '}',
          '',
          '// THE WINDOW. Opened from the quest tab: Server Statistics, Quick actions',
          '// (questtab/scripts/questtab.rs2).',
          '[proc,boss_kills_open]',
          'if_openmain(%s);' % IFACE,
          'def_int $total = 0;']
    for i in range(len(B)):
        L.append('$total = add($total, ~boss_kills_count(%s:count%d, ~boss_kill_get(%d)));' % (IFACE, i, i))
    L += ['if_settext(%s:subtitle, "Total boss kills: @yel@<~tp_gp($total)>");' % IFACE,
          '',
          "// One box's count: right-aligned in its box, yellow once there is a kill and grey before.",
          '[proc,boss_kills_count](component $com, int $kills)(int)',
          'def_string $text = ~tp_gp($kills);',
          'if_settext($com, $text);',
          'if_setposition($com, max(0, sub(%d, stringwidth($text, b12_full))), 0);' % (BOX_W - 2 * PAD),
          'if ($kills > 0) {',
          '    if_setcolour($com, ^yellow_rgb);',
          '} else {',
          '    if_setcolour($com, 0x8F8F8F);',
          '}',
          'return($kills);',
          '']
    return '\n'.join(L)


def patch_questlist(spec, check):
    """Take this generator's old "Boss kill counts" row back OUT of the quest list.

    The row was appended here until the quest tab got pages of its own (tools/genquesttab.py): the
    window opens from Server Statistics' Quick actions now, and the quest list is quests only. The
    removal stays so that a checkout still carrying the row loses it on the next run. The block runs
    from its marker comment to the next block header at column 0, or to the end of the file.
    """
    txt = read(QUESTLIST)
    old = re.search(r'(?ms)\n*// APPENDED by tools/genbosskills\.py.*?\n\[%s\]\n'
                    r'(?:(?!\n\[).)*(?=\n\[|\Z)' % re.escape(QL_ROW), txt)
    if old:
        txt = (txt[:old.start()] + txt[old.end():]).rstrip('\n') + '\n'
    return txt


def take(path, names, check, crlf=False):
    """Give every name an id in a tracked pack file, keeping the ones it already has."""
    txt = read(path)
    have = {n: int(i) for i, n in re.findall(r'^(\d+)=(\S+)$', txt, re.M)}
    used = set(have.values())
    nxt = (max(used) + 1) if used else 0
    added = []
    for n in names:
        if n in have:
            continue
        while nxt in used:
            nxt += 1
        have[n] = nxt
        used.add(nxt)
        added.append('%d=%s' % (nxt, n))
    lines = ['%d=%s' % (i, n) for n, i in sorted(have.items(), key=lambda kv: kv[1])]
    if not check and added:
        open(path, 'w', newline='').write('\n'.join(lines) + '\n')
    return have, added


def take_order(path, ids, check):
    txt = read(path)
    cur = [int(x) for x in txt.split('\n') if x.strip().isdigit()]
    want = sorted(set(cur) | set(ids))
    if not check and want != cur:
        open(path, 'w', newline='').write('\n'.join(str(i) for i in want) + '\n')
    return want != cur


def main():
    check = '--check' in sys.argv
    spec = json.load(open(SPEC))
    iftext, ifnames = build_if(spec)
    want = {OUT_VARP: build_varp(spec), OUT_CONST: build_const(spec),
            OUT_ENUM: build_enum(spec), OUT_IF: iftext, OUT_RS2: build_rs2(spec)}
    qtext = patch_questlist(spec, check)
    want[QUESTLIST] = qtext

    varps = ['boss_kc_%s' % b['key'] for b in spec['bosses']]
    ifall = [IFACE] + ['%s:%s' % (IFACE, n) for n in ifnames]

    if check:
        bad = []
        for path, body in want.items():
            have = read(path) if os.path.exists(path) else None
            if have != body:
                bad.append(os.path.relpath(path, C))
        _, a1 = take(VARPPACK, varps, True)
        _, a2 = take(IFPACK, ifall, True)
        if a1:
            bad.append('varp.pack is missing %s' % ', '.join(a1))
        if a2:
            bad.append('interface.pack is missing %s' % ', '.join(a2))
        if bad:
            print('genbosskills --check: ' + '; '.join(bad))
            return 1
        print('genbosskills --check: every generated file and both pack files are already what '
              'this writes')
        return 0

    for path, body in want.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, 'w', newline='').write(body)
        print('wrote %s' % os.path.relpath(path, C))
    _, a1 = take(VARPPACK, varps, False)
    # ifids rather than take(): a relayout drops components too, and the packer builds an empty
    # component for every name the pack still has
    sys.path.insert(0, os.path.join(C, 'tools'))
    import ifids
    for line in ifids.sync([IFACE, 'questlist']):
        print(line)
    print('%d bosses, %d components, %d varp ids'
          % (len(spec['bosses']), len(ifnames), len(a1)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
