#!/usr/bin/env python3
"""The quest tab's five pages: write every generated file for them.

    python3 tools/genquesttab.py            # write the files and take interface ids
    python3 tools/genquesttab.py --check     # exit 1 if anything would change

THE TAB. The quest journal slot (^tab_quest_journal) shows one of five side interfaces, each with the
same row of five stone buttons across the top - the lit one is the page you are on - and a title:

  0 questtab_summary      Character Summary - name, levels, XP, quests, the collection log, game mode
  1 questlist             Quests - the quest list itself, GENERATED by LostCityServer
                          tools/models/genquest474.py, which lays it out under the button row
  2 questtab_collection   Collection Log - progress per collection log tab, the latest item, a button
  3 questtab_pstats       Player Statistics - a table of counters (player/scripts/player_stats.rs2)
  4 questtab_sstats       Server Statistics - players online, the time, uptime, and quick actions

Pressing a button is if_settab with the other interface (questtab/scripts/questtab.rs2 fills its
texts first), so each page is an ordinary side interface and nothing is hidden or shown.

WHAT THIS WRITES
  * sprites/questtab_icons.png    the five 15x15 button icons: the Quests star from the world map's
                                  quest icon (mapfunction 6), and the same star hue-shifted for the
                                  other four - purple, green, red and gold - as Old School gives each
                                  of its quest tab pages the same gem in its own colour
  * sprites/questtab_tab.png      the 36x24 button stones - at rest, lit, under the mouse - and
  * sprites/questtab_button.png   the 182x26 wide button: both cut from 377's own grey and red
                                  combat-style stones (combatboxes), which is what a pressable
                                  button looks like everywhere else in this client
  * scripts/questtab/interfaces/questtab_{summary,collection,pstats,sstats}.if
  * scripts/interfaces/questlist.if    ONLY its own marked block (the button row), put back in the
                                  same place - immediately before [qp] - so the three generators
                                  that share that file (genquest474, genbosskills, gencollectionlog)
                                  can run in any order and it comes out the same
  * scripts/questtab/configs/questtab.constant, questtab.enum   page numbers and the Collection Log
                                  rows' components, which the script reaches by number
  * scripts/questtab/scripts/questtab_tabs.rs2    the button row's triggers and ~questtab_settab
  * pack/interface.pack, interface.order    ids, by way of tools/ifids.py

The collection log's tab count and names come from tools/collectionlogspec.json, so a fifth tab
there is a fifth row here on the next run.
"""
import colorsys, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ifids

C = os.path.dirname(HERE)
SPRITES = os.path.join(C, 'sprites')
DIR = os.path.join(C, 'scripts', 'questtab')
QUESTLIST = os.path.join(C, 'scripts', 'interfaces', 'questlist.if')
CLOGSPEC = os.path.join(C, 'tools', 'collectionlogspec.json')
KEY = (255, 0, 255)
OUTLINE, BEVEL = (46, 43, 35), (114, 100, 81)   # combatboxes' stone: its outline and bevel line

# ------------------------------------------------------------------------------------ the pages
# (constant, interface, button option / title)
PAGES = [('summary', 'questtab_summary', 'Character Summary'),
         ('quests', 'questlist', 'Quests'),
         ('collection', 'questtab_collection', 'Collection Log'),
         ('pstats', 'questtab_pstats', 'Player Statistics'),
         ('sstats', 'questtab_sstats', 'Server Statistics')]

# ------------------------------------------------------------------------------------ geometry
# The side panel is 190x261. The button row is five 36x24 stones a pixel apart, 3px in from each
# side; the title sits under it where 474's "Quest Points" did above the list, and every page's
# body starts at BODY_TOP. genquest474.py imports these so the quest list lines up with the rest.
TAB_X, TAB_Y, TAB_W, TAB_H, TAB_PITCH = 3, 3, 36, 24, 37
TITLE_X, TITLE_Y, TITLE_W, TITLE_H = 6, 30, 178, 15
BODY_TOP, BODY_BOTTOM = 46, 257
BOX_X, BOX_W = 4, 182

# 474's title orange (the quest list's "Quest Points" is this colour), the client's text orange,
# and the rest of the palette the pages use.
TITLE = '0xEB981F'
ORANGE, WHITE, YELLOW, GREEN = '0xFF981F', '0xFFFFFF', '0xFFFF00', '0x00FF00'
# The stone buttons' own two edge colours (combatboxes): the dark outline and the brown bevel. A box
# is drawn in the same two, the other way up - dark along the top and left, brown along the bottom
# and right - so a box reads as set INTO the stone and a button as standing out of it.
EDGE, RIM = '0x2E2B23', '0x726451'
RULE = '0x4A4033'
TRACK = '0x1E1A14'


# ------------------------------------------------------------------------------------ sprites
def load_rgb(name):
    from PIL import Image
    return Image.open(os.path.join(SPRITES, name + '.png')).convert('RGB')


def icons():
    """The five button icons, in page order."""
    star = load_rgb('mapfunction').crop((90, 0, 105, 15))

    def is_star(p):
        r, g, b = p
        return b > r + 30 and b > g + 20          # the star's five blues; the grey coin is not

    def recolour(hue, sat=1.0, val=1.0):
        im = star.copy()
        px = im.load()
        for y in range(15):
            for x in range(15):
                p = px[x, y]
                if p != KEY and is_star(p):
                    h, s, v = colorsys.rgb_to_hsv(*(c / 255 for c in p))
                    r, g, b = colorsys.hsv_to_rgb(hue / 360, min(1, s * sat), min(1, v * val))
                    px[x, y] = (round(r * 255), round(g * 255), round(b * 255))
        return im
    return [recolour(285, 1.0, 0.95), star, recolour(125, 1.05, 0.8), recolour(0, 1.05, 0.9),
            recolour(45, 1.1, 0.95)]


def stone(src, w, h, lift=0):
    """A w x h button cut from a combatboxes stone: the notched corners as they are, the edges and
    the face TILED rather than stretched, so the stone keeps its grain at any size. lift brightens
    the stone but not its outline or bevel line - the under-the-mouse state."""
    from PIL import Image
    s = src.crop((2, 2, 70, 34))              # the stone inside its 72x36 tile (the rest is key)
    sw, sh, k = s.width, s.height, 5          # k: the notched corner and its two edge lines
    out = Image.new('RGB', (w, h), KEY)

    def tile(region, dx, dy, dw, dh):
        piece = s.crop(region)
        for yy in range(dy, dy + dh, piece.height):
            for xx in range(dx, dx + dw, piece.width):
                out.paste(piece.crop((0, 0, min(piece.width, dx + dw - xx), min(piece.height, dy + dh - yy))), (xx, yy))
    tile((k, k, sw - k, sh - k), k, k, w - 2 * k, h - 2 * k)                 # face
    tile((k, 0, sw - k, k), k, 0, w - 2 * k, k)                               # top
    tile((k, sh - k, sw - k, sh), k, h - k, w - 2 * k, k)                     # bottom
    tile((0, k, k, sh - k), 0, k, k, h - 2 * k)                               # left
    tile((sw - k, k, sw, sh - k), w - k, k, k, h - 2 * k)                     # right
    for cx, cy in ((0, 0), (w - k, 0), (0, h - k), (w - k, h - k)):          # corners
        sx = 0 if cx == 0 else sw - k
        sy = 0 if cy == 0 else sh - k
        out.paste(s.crop((sx, sy, sx + k, sy + k)), (cx, cy))
    if lift:
        px = out.load()
        for yy in range(h):
            for xx in range(w):
                p = px[xx, yy]
                if p not in (KEY, OUTLINE, BEVEL):
                    px[xx, yy] = tuple(min(255, c + lift) for c in p)
    return out


def sheet(tiles):
    from PIL import Image
    w, h = tiles[0].size
    out = Image.new('RGB', (w * len(tiles), h), KEY)
    for i, t in enumerate(tiles):
        out.paste(t, (i * w, 0))
    return out


def sprites():
    """{name: (image, 'WxH')}"""
    cb = load_rgb('combatboxes')
    grey, red = cb.crop((0, 0, 72, 36)), cb.crop((72, 0, 144, 36))
    return {
        'questtab_icons': (sheet(icons()), '15x15'),
        'questtab_tab': (sheet([stone(grey, TAB_W, TAB_H), stone(red, TAB_W, TAB_H), stone(grey, TAB_W, TAB_H, 36)]),
                         '%dx%d' % (TAB_W, TAB_H)),
        'questtab_button': (sheet([stone(grey, BOX_W, 26), stone(grey, BOX_W, 26, 30)]), '%dx26' % BOX_W),
    }


# ------------------------------------------------------------------------------------ components
class Page:
    """One interface's components, in draw order."""

    def __init__(self, active):
        self.coms = []
        self.active = active

    def add(self, name, **kv):
        self.coms.append((name, kv))

    # -- the parts every page has
    def tabs(self):
        """The button row. The page's own button is the lit stone with no option; the others are
        buttons, and each shows its lit copy (a hidden layer, <name>_hover) under the mouse - the way
        house_options.if lights its close X."""
        for k, (_, _, label) in enumerate(PAGES):
            x = TAB_X + k * TAB_PITCH
            n = 'tab_%s' % PAGES[k][0]
            if k == self.active:
                self.add(n, type='graphic', x=x, y=TAB_Y, width=TAB_W, height=TAB_H, graphic='questtab_tab,1')
            else:
                self.add(n, type='graphic', x=x, y=TAB_Y, buttontype='normal', overlayer=n + '_hover',
                         width=TAB_W, height=TAB_H, graphic='questtab_tab,0', option=label)
            self.add(n + '_icon', type='graphic', x=x + 11, y=TAB_Y + 4, width=15, height=15,
                     graphic='questtab_icons,%d' % k)
        # the lit copies last, so they draw over the row
        for k in range(len(PAGES)):
            if k == self.active:
                continue
            x = TAB_X + k * TAB_PITCH
            n = 'tab_%s' % PAGES[k][0]
            self.add(n + '_hover', type='layer', x=x, y=TAB_Y, width=TAB_W, height=TAB_H, hide='yes')
            self.add(n + '_lit', layer=n + '_hover', type='graphic', x=0, y=0, width=TAB_W, height=TAB_H,
                     graphic='questtab_tab,2')
            self.add(n + '_lit_icon', layer=n + '_hover', type='graphic', x=11, y=4, width=15, height=15,
                     graphic='questtab_icons,%d' % k)

    def title(self, text):
        self.add('title', type='text', x=TITLE_X, y=TITLE_Y, width=TITLE_W, height=TITLE_H, font='b12_full',
                 shadowed='yes', text=text, colour=TITLE)

    # -- building blocks
    def box(self, name, x, y, w, h, dark=146):
        """A box set into the stone: a translucent black face (dark is the old format's trans - 0
        opaque, 255 invisible) inside a 1px rim, dark along the top and left, brown along the
        bottom and right."""
        self.add(name, type='rect', x=x + 1, y=y + 1, width=w - 2, height=h - 2, fill='yes', colour='0x000000',
                 trans=dark)
        self.add(name + '_rim', type='rect', x=x, y=y, width=w, height=h, colour=RIM)
        self.add(name + '_top', type='rect', x=x, y=y, width=w - 1, height=1, fill='yes', colour=EDGE)
        self.add(name + '_left', type='rect', x=x, y=y, width=1, height=h - 1, fill='yes', colour=EDGE)

    def text(self, name, x, y, w, text='', colour=ORANGE, font='p12_full', center=False, h=15, **kv):
        d = dict(type='text', x=x, y=y, width=w, height=h)
        d.update(kv)
        if center:
            d['center'] = 'yes'
        d.update(font=font, shadowed='yes', text=text, colour=colour)
        self.coms.append((name, d))

    def button(self, name, x, y, label, option, icon=None):
        """The wide stone button: the grey stone, its label, and - under the mouse - the lit stone
        with the label in white."""
        self.add(name, type='graphic', x=x, y=y, buttontype='normal', overlayer=name + '_hover', width=BOX_W,
                 height=26, graphic='questtab_button,0', option=option)
        if icon is not None:
            self.add(name + '_icon1', type='graphic', x=x + 8, y=y + 5, width=15, height=15,
                     graphic='questtab_icons,%d' % icon)
            self.add(name + '_icon2', type='graphic', x=x + BOX_W - 23, y=y + 5, width=15, height=15,
                     graphic='questtab_icons,%d' % icon)
        self.text(name + '_label', x, y + 6, BOX_W, label, ORANGE, 'b12_full', center=True)
        self.add(name + '_hover', type='layer', x=x, y=y, width=BOX_W, height=26, hide='yes')
        self.add(name + '_lit', layer=name + '_hover', type='graphic', x=0, y=0, width=BOX_W, height=26,
                 graphic='questtab_button,1')
        if icon is not None:
            self.add(name + '_lit_icon1', layer=name + '_hover', type='graphic', x=8, y=5, width=15, height=15,
                     graphic='questtab_icons,%d' % icon)
            self.add(name + '_lit_icon2', layer=name + '_hover', type='graphic', x=BOX_W - 23, y=5, width=15,
                     height=15, graphic='questtab_icons,%d' % icon)
        self.text(name + '_lit_label', 0, 6, BOX_W, label, WHITE, 'b12_full', center=True, layer=name + '_hover')

    def link(self, name, x, y, w, label, option, h=19):
        """A row of the Quick actions list: its text, and under the mouse a lit strip behind it with
        the text in white."""
        self.add(name, type='rect', x=x, y=y, buttontype='normal', overlayer=name + '_hover', width=w, height=h,
                 fill='yes', colour='0x000000', trans=255, option=option)
        self.text(name + '_label', x + 8, y + 2, w - 8, label, ORANGE)
        self.add(name + '_hover', type='layer', x=x, y=y, width=w, height=h, hide='yes')
        self.add(name + '_lit', layer=name + '_hover', type='rect', x=0, y=0, width=w, height=h, fill='yes',
                 colour='0x8C7F63', trans=190)
        self.text(name + '_lit_label', 8, 2, w - 8, label, WHITE, layer=name + '_hover')


def summary():
    p = Page(0)
    p.tabs()
    p.title('Character Summary')
    p.box('name_box', BOX_X, 46, BOX_W, 20, dark=40)
    p.text('name', BOX_X, 49, BOX_W, '', YELLOW, 'b12_full', center=True)
    for key, x, label, colour, y in (('combat', 4, 'Combat Level', WHITE, 69), ('total', 96, 'Total Level', WHITE, 69),
                                     ('quests', 4, 'Quests Done', GREEN, 129), ('qp', 96, 'Quest Points', GREEN, 129)):
        p.box(key + '_box', x, y, 90, 34)
        p.text(key + '_label', x, y + 3, 90, label, ORANGE, center=True)
        p.text(key, x, y + 17, 90, '', colour, center=True)
    p.box('xp_box', BOX_X, 106, BOX_W, 20)
    p.text('xp', BOX_X, 109, BOX_W, '', ORANGE, center=True)
    p.button('collog', BOX_X, 166, 'Collection Log', 'Open @lre@Collection Log', icon=2)
    p.box('collections_box', BOX_X, 195, BOX_W, 20)
    p.text('collections', BOX_X, 198, BOX_W, '', ORANGE, center=True)
    p.box('mode_box', BOX_X, 218, BOX_W, 20)
    p.text('mode', BOX_X, 221, BOX_W, '', ORANGE, center=True)
    p.box('online_box', BOX_X, 241, BOX_W, 17, dark=40)
    p.text('online', BOX_X, 242, BOX_W, '', ORANGE, center=True)
    return p


# The Collection Log page's rows, one per collection log tab.
CL_ROW_Y, CL_ROW_PITCH, CL_ROW_H = 70, 28, 25
CL_BAR_X, CL_BAR_W = 11, 168
CL_COUNT_X, CL_COUNT_W = 100, 78


def collection(tabs):
    p = Page(2)
    p.tabs()
    p.title('Collection Log')
    p.box('obtained_box', BOX_X, 46, BOX_W, 20, dark=40)
    p.text('obtained', BOX_X, 49, BOX_W, '', ORANGE, 'b12_full', center=True)
    for k in range(len(tabs)):
        y = CL_ROW_Y + k * CL_ROW_PITCH
        p.box('row%d_box' % k, BOX_X, y, BOX_W, CL_ROW_H)
        p.text('row%d_name' % k, 12, y + 3, 88, '', ORANGE)
        # right-aligned by ~questtab_right, which moves it by the width it does not fill
        p.text('row%d_count' % k, CL_COUNT_X, y + 3, CL_COUNT_W, '', WHITE)
        # the bar: a dark track, and the fill over it moved left by the part not yet obtained - the
        # layer clips it, so what shows is exactly the obtained share
        p.add('row%d_bar' % k, type='layer', x=CL_BAR_X, y=y + 19, width=CL_BAR_W, height=2)
        p.add('row%d_track' % k, layer='row%d_bar' % k, type='rect', x=0, y=0, width=CL_BAR_W, height=2,
              fill='yes', colour=TRACK)
        p.add('row%d_fill' % k, layer='row%d_bar' % k, type='rect', x=0, y=0, width=CL_BAR_W, height=2,
              fill='yes', colour=GREEN)
    y = CL_ROW_Y + len(tabs) * CL_ROW_PITCH
    p.box('latest_box', BOX_X, y, BOX_W, 34)
    p.text('latest_label', BOX_X, y + 3, BOX_W, 'Latest item logged', ORANGE, center=True)
    p.text('latest', BOX_X, y + 17, BOX_W, '', WHITE, center=True)
    p.button('open', BOX_X, BODY_BOTTOM - 26, 'Open Collection Log', 'Open @lre@Collection Log')
    return p


# The Player Statistics rows: (key, label). The values are filled by ~questtab_pstats_draw.
PSTATS = [('mode', 'Game mode'), ('rate', 'XP rate'), ('drops', 'Drop rates'), ('playtime', 'Time played'),
          ('age', 'Account age'),
          ('locked', 'XP locked'), ('deaths', 'Deaths'), ('pvp', 'Players killed'), ('npcs', 'Monsters killed'),
          ('clues', 'Clues opened'), ('bosses', 'Boss kills'), ('slayer', 'Slayer tasks'),
          ('slpoints', 'Slayer points'), ('bank', 'Bank value')]
# fourteen rows at 15px fill the box from its top edge to its bottom one (thirteen were at 16px until
# the game mode's drop-rate boost got a row of its own under the XP rate). They start 2px higher than
# the thirteen did, so the first and last rows each sit 3px inside the box's rim rather than the last
# row's shadow touching it.
PS_Y, PS_PITCH = 47, 15
PS_VALUE_X, PS_VALUE_W = 96, 84


def pstats():
    p = Page(3)
    p.tabs()
    p.title('Player Statistics')
    p.box('list_box', BOX_X, BODY_TOP, BOX_W, BODY_BOTTOM - BODY_TOP)
    for k, (key, label) in enumerate(PSTATS):
        y = PS_Y + k * PS_PITCH
        p.text(key + '_label', 10, y, 86, label, ORANGE)
        p.text(key, PS_VALUE_X, y, PS_VALUE_W, '', WHITE)
        if k < len(PSTATS) - 1:
            p.add(key + '_rule', type='rect', x=9, y=y + PS_PITCH - 1, width=BOX_W - 10, height=1, fill='yes',
                  colour=RULE)
    return p


# Server Statistics' Quick actions: (key, label, option). Report a player and Discord, in the mock-up,
# are not here: the server cannot open the client's report window (the client only arms its typing
# for the window when it opened it itself), and there is no Discord invite anywhere to point at.
ACTIONS = [('drops', 'View monster drop tables', 'View @lre@Monster drop tables'),
           ('bosses', 'View boss kill counts', 'View @lre@Boss kill counts'),
           ('collog', 'Open collection log', 'Open @lre@Collection Log'),
           ('mode', 'Game mode & XP rate', 'View @lre@Game mode & XP rate')]


def sstats():
    p = Page(4)
    p.tabs()
    p.title('Server Statistics')
    for k, (key, dark) in enumerate((('online', 40), ('time', 146), ('uptime', 146), ('slogan', 146))):
        y = BODY_TOP + k * 23
        p.box(key + '_box', BOX_X, y, BOX_W, 20, dark=dark)
        p.text(key, BOX_X, y + 3, BOX_W, 'The true golden era.' if key == 'slogan' else '',
               YELLOW if key == 'slogan' else ORANGE, center=True)
    top = BODY_TOP + 4 * 23 + 2
    p.box('actions_box', BOX_X, top, BOX_W, BODY_BOTTOM - top)
    p.text('actions_title', 10, top + 4, 170, 'Quick actions', YELLOW, 'b12_full')
    for k, (key, label, option) in enumerate(ACTIONS):
        y = top + 22 + k * 21
        if k:
            p.add('act_%s_rule' % key, type='rect', x=BOX_X + 6, y=y - 1, width=BOX_W - 12, height=1, fill='yes',
                  colour=RULE)
        p.link('act_' + key, BOX_X + 3, y, BOX_W - 6, label, option)
    return p


# ------------------------------------------------------------------------------------ writers
ORDER = ['layer', 'type', 'x', 'y', 'buttontype', 'overlayer', 'width', 'height', 'hide', 'center', 'font',
         'shadowed', 'fill', 'graphic', 'text', 'colour', 'trans', 'option']


def emit(coms):
    out = []
    for name, c in coms:
        out.append('[%s]' % name)
        for k in ORDER:
            if k in c:
                out.append('%s=%s' % (k, c[k]))
        extra = [k for k in c if k not in ORDER]
        if extra:
            raise SystemExit('genquesttab: unknown interface key %s on %s' % (extra, name))
        out.append('')
    return '\n'.join(out).rstrip('\n') + '\n'


HEAD = ('// GENERATED by tools/genquesttab.py - do not hand-edit. The quest tab\'s %s page; its texts are\n'
        '// filled by questtab/scripts/questtab.rs2 each time it is shown.\n')


def interfaces(tabs):
    return {'questtab_summary': summary(), 'questtab_collection': collection(tabs), 'questtab_pstats': pstats(),
            'questtab_sstats': sstats()}


MARK = '// APPENDED by tools/genquesttab.py'


def patch_questlist(text):
    """The button row, in its own marked block immediately before [qp]. [qp] is genquest474's, and
    neither genbosskills nor gencollectionlog goes near it (they work at the end of the file), so
    all four generators can run in any order and the file comes out the same."""
    t = text.replace('\r\n', '\n')
    i = t.find(MARK)
    if i >= 0:
        end = t.find('\n[qp]\n', i)
        if end < 0:
            raise SystemExit('genquesttab: my block in questlist.if is not followed by [qp]')
        t = t[:i].rstrip('\n') + '\n\n' + t[end + 1:]
    at = t.find('\n[qp]\n')
    if at < 0:
        raise SystemExit('genquesttab: questlist.if has no [qp] - run LostCityServer tools/models/genquest474.py')
    p = Page(1)
    p.tabs()
    block = (MARK + ' - do not hand-edit. The quest tab\'s button row, the same on all five\n'
             '// pages; the triggers are in questtab/scripts/questtab_tabs.rs2.\n' + emit(p.coms))
    return t[:at + 1] + block + '\n' + t[at + 1:]


def build_constant():
    L = ['// GENERATED by tools/genquesttab.py - do not hand-edit.',
         '//',
         '// The quest tab\'s pages, in the order of the button row. %questtab_page holds one of these.']
    for k, (key, _, _) in enumerate(PAGES):
        L.append('^questtab_%s = %d' % (key, k))
    L.append('^questtab_pages = %d' % len(PAGES))
    L.append('')
    L.append('// The Collection Log page\'s bar: its width, and the pixels the fill is moved left by for a share of it.')
    L.append('^questtab_bar_width = %d' % CL_BAR_W)
    L.append('// How far right-aligned values reach: each value component starts at x and is this wide.')
    L.append('^questtab_pstats_value_width = %d' % PS_VALUE_W)
    L.append('^questtab_collection_count_width = %d' % CL_COUNT_W)
    # These two were added to the .constant by hand (the refresh timer, the text-overflow fixes), so a
    # rerun of this dropped them and broke the build - they are written from here now.
    L.append('')
    L.append('// How often the page on show is refilled ([softtimer,questtab_refresh]): 5 ticks, three seconds.')
    L.append('^questtab_refresh_ticks = 5')
    L.append('')
    L.append("// The widest a centred line may be inside one of the pages' %dpx boxes without touching its rim." % BOX_W)
    L.append('^questtab_text_width = %d' % (BOX_W - 6))
    return '\n'.join(L) + '\n'


def build_enum(tabs):
    L = ['// GENERATED by tools/genquesttab.py - do not hand-edit.',
         '//',
         '// The Collection Log page\'s rows by collection log tab number, so ~questtab_collection_draw can',
         '// walk the tabs rather than name each row: the engine cannot pick a component by number.']
    for what in ('name', 'count', 'fill'):
        L += ['', '[questtab_collection_%s]' % what, 'inputtype=int', 'outputtype=component']
        for k in range(len(tabs)):
            L.append('val=%d,questtab_collection:row%d_%s' % (k, k, what))
    return '\n'.join(L) + '\n'


def build_rs2():
    L = ['// GENERATED by tools/genquesttab.py - do not hand-edit.',
         '//',
         '// The quest tab\'s button row: on every page, each of the other four buttons selects its page.',
         '// The page\'s own button is not a button, so it has no trigger.',
         '',
         '// Show a page\'s interface in the quest tab slot. ~questtab_show fills its texts first.',
         '[proc,questtab_settab](int $page)',
         'switch_int ($page) {']
    for key, iface, _ in PAGES:
        L.append('    case ^questtab_%s : if_settab(%s, ^tab_quest_journal);' % (key, iface))
    L.append('}')
    for _, iface, _ in PAGES:
        L.append('')
        for key, other, _ in PAGES:
            if other != iface:
                L.append('[if_button,%s:tab_%s] ~questtab_select(^questtab_%s);' % (iface, key, key))
    return '\n'.join(L) + '\n'


# ------------------------------------------------------------------------------------ main
def read(p):
    return open(p, encoding='utf-8', newline='').read() if os.path.exists(p) else None


def crlf_of(path, like):
    t = read(path) if os.path.exists(path) else read(like)
    return t is not None and '\r\n' in t


def main():
    check = '--check' in sys.argv
    tabs = json.load(open(CLOGSPEC, encoding='utf-8'))['tabs']
    like = QUESTLIST
    want = {}
    for name, page in interfaces(tabs).items():
        which = name.split('_', 1)[1]
        want[os.path.join(DIR, 'interfaces', name + '.if')] = HEAD % dict(summary='Character Summary',
            collection='Collection Log', pstats='Player Statistics', sstats='Server Statistics')[which] + emit(page.coms)
    want[os.path.join(DIR, 'configs', 'questtab.constant')] = build_constant()
    want[os.path.join(DIR, 'configs', 'questtab.enum')] = build_enum(tabs)
    want[os.path.join(DIR, 'scripts', 'questtab_tabs.rs2')] = build_rs2()
    want[QUESTLIST] = patch_questlist(read(QUESTLIST))

    changed = []
    for path, body in want.items():
        nl = '\r\n' if crlf_of(path, like) else '\n'
        body = body.replace('\r\n', '\n').replace('\n', nl)
        if read(path) != body:
            changed.append(os.path.relpath(path, C))
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, 'w', encoding='utf-8', newline='').write(body)

    from PIL import Image, ImageChops
    for name, (img, opt) in sprites().items():
        png = os.path.join(SPRITES, name + '.png')
        meta = os.path.join(SPRITES, 'meta', name + '.opt')
        same = os.path.exists(png) and Image.open(png).convert('RGB').size == img.size and \
            ImageChops.difference(Image.open(png).convert('RGB'), img).getbbox() is None
        if not same:
            changed.append(os.path.relpath(png, C))
            if not check:
                img.save(png)
        if read(meta) is None or read(meta).strip() != opt:
            changed.append(os.path.relpath(meta, C))
            if not check:
                open(meta, 'w', newline='').write(opt + '\n')

    names = [p[1] for p in PAGES]
    if check:
        packed = set(re.findall(r'^\d+=(\S+?)\r?$', read(ifids.PACK), re.M))
        ids_ok = all(n in packed for n in names) and all(
            '%s:%s' % (n, c) in packed for n in names if n != 'questlist'
            for c, _ in interfaces(tabs)[n].coms)
        if changed or not ids_ok:
            print('genquesttab --check: would change %s' % ', '.join(changed + ([] if ids_ok else ['interface.pack'])))
            return 1
        print('genquesttab --check: everything is already what this writes')
        return 0
    for line in ifids.sync(names):
        print(line)
    print('genquesttab: %d files changed%s' % (len(changed), ''.join('\n  ' + c for c in changed)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
